In [1]:
import numpy as np
print(np.__version__)

1.19.2


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
#Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

42


In [4]:
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [5]:
#reate a 2-D array containing two arrays 

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#Create a 3-D array with two 2-D arrays,

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#Get the first element 

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [8]:
#Get the second element 

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [9]:
#Get third and fourth elements 

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [10]:
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [11]:
#Slice from the index 3 from the end to index 1 from the end

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [12]:
#Return every other element from index 1 to index 5

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


In [13]:
#Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [14]:
#Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


In [15]:
#Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [16]:
#Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [17]:
#Create an array with 5 dimensions using ndmin

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [18]:
#Convert the following 1-D array with 12 elements into a 2-D array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
#Convert the following 1-D array with 12 elements into a 3-D array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
#Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [22]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [23]:
#Split the array in 3 parts

import numpy as np

arr = np.array([1, 2,  5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([5]), array([6])]


In [26]:
#Split the 2-D array into three 2-D arrays along rows

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [27]:
#Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [28]:
#Find the indexes where the values are even:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 6], dtype=int64),)


In [30]:
#Find the indexes where the values are odd:
import numpy as np
arr = np.array([1, 2, 3,  6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4], dtype=int64),)


In [31]:
#Find the indexes where the values 2, 4, and 6 should be inserted:
import numpy as np
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [32]:
#Sort the array:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [33]:
#ort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [34]:
#Sort a boolean array:
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [35]:
#Sort a 2-D array:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [36]:
#Create an array from the elements on index 0 and 2:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)


[41 43]


In [37]:
#Create a filter array that will return only values higher than 42:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [38]:
#Generate a random integer from 0 to 100:
from numpy import random
x = random.randint(100)
print(x)

26


In [39]:
#Generate a 1-D array containing 5 random integers from 0 to 100:
from numpy import random
x=random.randint(100, size=(5))
print(x)


[63 79 30 45 27]


In [40]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers:
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.2022785  0.98576041 0.71109461 0.63737204 0.46432705]
 [0.48450872 0.35944261 0.95094109 0.24905149 0.05247858]
 [0.49104319 0.97695794 0.78927739 0.29518105 0.46873459]]


In [41]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 5 7 3 3]
 [5 9 7 3 9]
 [9 3 7 9 5]]


In [42]:
#Randomly shuffle elements of following array:

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[5 2 3 4 1]


In [46]:
#Convert following array with repeated elements to a set:

import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [47]:
#Reshaping an array into two rows:
a = np.arange(100)
b = np.reshape(a, (2, -1))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [52]:
#Find sine values for all of the values in arr:

import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [53]:
for element in b.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [54]:
for i in a:
...     print(i**(1/3.))

0.0
1.0
1.2599210498948732
1.4422495703074083
1.5874010519681994
1.7099759466766968
1.8171205928321397
1.912931182772389
2.0
2.080083823051904
2.154434690031884
2.2239800905693152
2.2894284851066637
2.3513346877207573
2.4101422641752297
2.46621207433047
2.5198420997897464
2.571281590658235
2.6207413942088964
2.668401648721945
2.7144176165949063
2.7589241763811203
2.802039330655387
2.8438669798515654
2.8844991406148166
2.924017738212866
2.9624960684073702
3.0
3.0365889718756622
3.072316825685847
3.1072325059538586
3.1413806523913927
3.1748021039363987
3.207534329995826
3.239611801277483
3.2710663101885897
3.3019272488946263
3.332221851645953
3.361975406798963
3.3912114430141664
3.4199518933533937
3.4482172403827303
3.4760266448864496
3.503398060386724
3.530348335326063
3.5568933044900626
3.583047871015946
3.6088260801386944
3.634241185664279
3.6593057100229713
3.6840314986403864
3.708429769266189
3.7325111568172478
3.756285754221072
3.7797631496846193
3.802952460761391
3.825862365544778